apiVersion: apps/v1
kind: Deployment
metadata:
  name: byodc
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.byodc.config.replicas }}
  selector:
    matchLabels:
      app: byodc
  template:
    metadata:
      labels:
        app: byodc
    spec:
      {{- if .Values.byodc.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.byodc.image.pullSecret }}
      {{- end }}
      containers:
        - name: byodc
          {{- if .Values.local }}
          imagePullPolicy: IfNotPresent
          {{- end }}
          {{- if .Values.byodc.image.tag }}
          image: {{ .Values.byodc.image.name }}:{{ .Values.byodc.image.tag -}}
          {{- else}}
          image: {{ .Values.byodc.image.name }}:{{ .Chart.Version -}}
          {{- end }}
          resources:
            limits:
            {{- range $key, $value := .Values.byodc.config.limits }}
              {{ $key }}: {{ $value }}
            {{- end }}
          ports:
            - containerPort: 80
          env:
            - name: Redis__ConnectionString
              value: {{ tpl .Values.byodc.config.redis.host . }}:{{ .Values.byodc.config.redis.port }}
            - name: Redis__Channel
              value: {{ .Values.byodc.config.redis.channel }}
              {{- with .Values.byodc.config.applicationInsights }}{{ if .instrumentationKey }}
            - name: ApplicationInsights__InstrumentationKey
              value: {{ .instrumentationKey }}
              {{- end }}{{ end }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.byodc.config.logLevel }}
            - name: Helipad__BaseUrl
              value: {{ .Values.byodc.config.helipad.baseUrl }}
              {{- with .Values.byodc.proxy }}{{ range $key, $value := . }}{{if $value }}
            - name: {{ $key | upper }}_PROXY
              value: {{ $value | quote }}
              {{- end }}{{ end }}{{ end }}
              {{- with .Values.byodc.config.env }}{{ range $value := . }}{{if $value }}
            - {{ toYaml $value | nindent 14 | trim -}}
              {{- end }}{{ end }}{{ end }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            failureThreshold: 30
            periodSeconds: 5
            
---
apiVersion: v1
kind: Service
metadata:
  name: byodc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: byodc
