apiVersion: getambassador.io/v2
kind: KubernetesEndpointResolver
metadata:
  name: ft-signaturecloud-resolver
  namespace: {{ .Release.Namespace }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  ambassador
  namespace: {{ .Release.Namespace }}
spec:
  prefix: {{ .Values.signaturecloud.config.prefix }}
  service: ft-signaturecloud.{{ .Release.Namespace }}:80
  resolver: ft-signaturecloud-resolver
  load_balancer:
    policy: ring_hash
    header: cashboxid
  timeout_ms: {{ .Values.signaturecloud.config.timeout.all }}
  connect_timeout_ms: {{ .Values.signaturecloud.config.timeout.connect }}
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: host
  namespace: {{ .Release.Namespace }}
spec:
  hostname: {{ .Values.ambassador.config.hostname | quote }}
  acmeProvider:
    authority: none
  {{- if .Values.ambassador.config.tls }}
  tlsSecret:
    name: tls-cert
  tls:
    min_tls_version: v1.2
  {{- else }}
  requestPolicy:
      insecure:
        action: Route
  {{- end }}
