apiVersion: getambassador.io/v2
kind: KubernetesEndpointResolver
metadata:
  name: byodc-resolver
  namespace: {{ .Release.Namespace }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  emissary
  namespace: {{ .Release.Namespace }}
spec:
  prefix: /
  service: byodc.{{ .Release.Namespace }}:80
  resolver: byodc-resolver
  load_balancer:
    policy: ring_hash
    header: cashboxid
  timeout_ms: {{ .Values.byodc.config.timeout.all }}
  connect_timeout_ms: {{ .Values.byodc.config.timeout.connect }}
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: host
  namespace: {{ .Release.Namespace }}
spec:
  hostname: {{ .Values.emissary.config.hostname | quote }}
  acmeProvider:
    authority: none
  {{- if .Values.emissary.config.tls.enabled }}
  tlsSecret:
    name: tls-cert
  tls:
    min_tls_version: v1.2
  {{- else }}
  requestPolicy:
      insecure:
        action: Route
  {{- end }}
