{{ with.Values.mysql }}{{ if .enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ $.Release.Namespace }}
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      {{- with $.Values.byodc.config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
{{- end }}{{ end }}
