apiVersion: v2
name: bring-your-own-datacenter
type: application
version: 1.3.34
kubeVersion: ^1.22.0
keywords:
  - fiskaltrust
  - byodc
  - bring-your-own-datacenter
home: https://github.com/fiskaltrust/product-de-bring-your-own-datacenter
sources:
  - https://github.com/fiskaltrust/helm-charts/tree/master/bring-your-own-datacenter
dependencies:
  - name: emissary-ingress
    version: 7.3.2
    repository: https://app.getambassador.io
    condition: emissary-ingress.install
