{{ if and (or .Values.loadbalancer.config.tls.crtBase64 .Values.loadbalancer.config.tls.crt) (or .Values.loadbalancer.config.tls.keyBase64 .Values.loadbalancer.config.tls.key ) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-cert
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.loadbalancer.config.tls.crtBase64 }}
  tls.crt: {{ .Values.loadbalancer.config.tls.crtBase64 }}
  {{- else }}
  tls.crt: {{ .Values.loadbalancer.config.tls.crt | b64enc }}
  {{- end }}

  {{- if .Values.loadbalancer.config.tls.keyBase64 }}
  tls.key: {{ .Values.loadbalancer.config.tls.keyBase64 }}
  {{- else }}
  tls.key: {{ .Values.loadbalancer.config.tls.key | b64enc }}
  {{- end }}
{{- end }}
