resources:
  repositories:
    - repository: self

pr:
  branches:
    include:
    - master
  paths:
    include:
    - '*'

trigger:
  tags:
    include:
    - '*'


steps:
- template: templates/build.yaml
  parameters:
    charts: 
      - bring-your-own-datacenter
